[CC]
CC_100_01p1m = "[C+0:1]-[C+0:2]>>[C+1:1].[C-1:2]"
CC_01p1m_100 = "[C+1:1].[C-1:2]>>[C+0:1]-[C+0:2]"
CC_200_11p1m = "[C+0:1]=[C+0:2]>>[C+1:1]-[C-1:2]"
CC_11p1m_200 = "[C+1:1]-[C-1:2]>>[C+0:1]=[C+0:2]"
CC_300_21p1m = "[C+0:1]#[C+0:2]>>[C+1:1]=[C-1:2]"
CC_21p1m_300 = "[C+1:1]=[C-1:2]>>[C+0:1]#[C+0:2]"

[HC]
HC_100_01p1m = "[H+0:1]-[C+0:2]>>[H+1:1].[C-1:2]"
HC_01p1m_100 = "[H+1:1].[C-1:2]>>[H+0:1]-[C+0:2]"

[CO]
CO_100_01p1m = "[C+0:1]-[O+0:2]>>[C+1:1].[O-1:2]"
CO_01p1m_100 = "[C+1:1].[O-1:2]>>[C+0:1]-[O+0:2]"
CO_101p_01p0 = "[C+0:1]-[O+1:2]>>[C+1:1].[O+0:2]"
CO_01p0_101p = "[C+1:1].[O+0:2]>>[C+0:1]-[O+1:2]"
CO_200_11p1m = "[C+0:1]=[O+0:2]>>[C+1:1]-[O-1:2]"
CO_11p1m_200 = "[C+1:1]-[O-1:2]>>[C+0:1]=[O+0:2]"
CO_201p_11p0 = "[C+0:1]=[O+1:2]>>[C+1:1]-[O+0:2]"
CO_11p0_201p = "[C+1:1]-[O+0:2]>>[C+0:1]=[O+1:2]"
CO_300_21p1m = "[C+0:1]#[O+0:2]>>[C+1:1]=[O-1:2]"
CO_21p1m_300 = "[C+1:1]=[O-1:2]>>[C+0:1]#[O+0:2]"

[OH]
OH_100_01m1p = "[O+0:1]-[H+0:2]>>[O-1:1].[H+1:2]"
OH_01m1p_100 = "[O-1:1].[H+1:2]>>[O+0:1]-[H+0:2]"
OH_11p0_001p = "[O+1:1]-[H+0:2]>>[O+0:1].[H+1:2]"
OH_001p_11p0 = "[O+0:1].[H+1:2]>>[O+1:1]-[H+0:2]"

[CN]
CN_100_01p1m = "[C+0:1]-[N+0:2]>>[C+1:1].[N-1:2]"
CN_01p1m_100 = "[C+1:1].[N-1:2]>>[C+0:1]-[N+0:2]"
CN_200_11p1m = "[C+0:1]=[N+0:2]>>[C+1:1]-[N-1:2]"
CN_11p1m_200 = "[C+1:1]-[N-1:2]>>[C+0:1]=[N+0:2]"
CN_300_21p1m = "[C+0:1]#[N+0:2]>>[C+1:1]=[N-1:2]"
CN_21p1m_300 = "[C+1:1]=[N-1:2]>>[C+0:1]#[N+0:2]"

[HN]
HN_100_01p1m = "[H+0:1]-[N+0:2]>>[H+1:1].[N-1:2]"
HN_01p1m_100 = "[H+1:1].[N-1:2]>>[H+0:1]-[N+0:2]"

[CBr]
CBr_dissociation = "[C+0:1]-[Br+0:2]>>[C+1:1].[Br-1:2]"
CBr_association  = "[C+1:1].[Br-1:2]>>[C+0:1]-[Br+0:2]"
CBr_101p_01p0 = "[C+0:1]-[Br+1:2]>>[C+1:1].[Br+0:2]"
CBr_01p0_101p = "[C+1:1].[Br+0:2]>>[C+0:1]-[Br+1;H0:2]"

[HBr]
HBr_dissociation = "[H+0:1]-[Br+0:2]>>[H+1:1].[Br-1:2]"
HBr_association  = "[H+1:1].[Br-1:2]>>[H+0:1]-[Br+0:2]"

[BrBr]
BrBr_dissociation = "[Br+0:1]-[Br+0:2]>>[Br+1;H0:1].[Br-1:2]"
BrBr_association  = "[Br+1:1].[Br-1:2]>>[Br+0:1]-[Br+0:2]"

[Rings_CC]
R3_CC  = "[C+0:1]1[*:2][C+0:3]1>>[C+1:1][*:2][C-1:3]"
R4_CC  = "[C+0:1]1[*:2][*:3][C+0:4]1>>[C+1:1][*:2][*:3][C-1:4]"
R5_CC  = "[C+0:1]1[*:2][*:3][*:4][C+0:5]1>>[C+1:1][*:2][*:3][*:4][C-1:5]"
R6_CC  = "[C+0:1]1[*:2][*:3][*:4][*:5][C+0:6]1>>[C+1:1][*:2][*:3][*:4][*:5][C-1:6]"

[Rings_CBr]
R3_CBr = "[C+0:1]1[*:2][Br+0:3]1>>[C+1:1][*:2][Br-1:3]"
R4_CBr = "[C+0:1]1[*:2][*:3][Br+0:4]1>>[C+1:1][*:2][*:3][Br-1:4]"
R5_CBr = "[C+0:1]1[*:2][*:3][*:4][Br+0:5]1>>[C+1:1][*:2][*:3][*:4][Br-1:5]"
R6_CBr = "[C+0:1]1[*:2][*:3][*:4][*:5][Br+0:6]1>>[C+1:1][*:2][*:3][*:4][*:5][Br-1:6]"
R3_CBrp="[C+0:1]1[*:2][Br+1:3]1>>[C+1:1][*:2][Br+0:3]"
R4_CBrp="[C+0:1]1[*:2][*:3][Br+1:4]1>>[C+1:1][*:2][*:3][Br+0:4]"
R5_CBrp="[C+0:1]1[*:2][*:3][*:4][Br+1:5]1>>[C+1:1][*:2][*:3][*:4][Br+0:5]"
R6_CBrp ="[C+0:1]1[*:2][*:3][*:4][*:5][Br+1:6]1>>[C+1:1][*:2][*:3][*:4][*:5][Br+0:6]"
